#+title:微分方程指南
#+author: King
#+start: 23.11.8
#+date: \today
#+latex_compiler:xlatex
#+latex_class: report
#+options: toc:t


* 概念总结
方程表示一种约束关系，它的解就是使方程成立的元素，在微分方程里往往是一个函数，它可能可以表达为显函数，或者只能写为隐函数，甚至于我们只能拿符号代替它的解。
能力有限，还没学过复变函数，所以只会初等的解法。

**  STARTED 目前对于一般的方程最一般的方法为： *幂级数解法*

文中一般使用 $x$ 为自变量。
#+TOC:headline 1
* 求解析解
一般手算思路
线性
+  $\rightarrow$ 计算齐次方程的特征方程解
无重根 $\rightarrow$ 得到 _齐次通解_
有重根 $\rightarrow$ 依据重数补齐
+ 非齐次- _特解_($y=y_h+y_p$)
  - 形式简单
    $\rightarrow$ 待定系数
  -  $\rightarrow$ 常数变易 $\rightarrow$ 解 Wronski 方程得到特解

非线性
已知特解：
$\rightarrow$ 常数变易


重根：
一般方法
# ?
d'Alembert /降阶法
# p127
$y_2(x)=v(x)y_1(x)$
$y_1$ 为已知形式的解


求出隐式解，那么根据初值条件代入，取最小的可能区间
** 一阶方程
直接积分
积分因子
*** 线性方程
形式： $P(x)y'+Q(x)y+R(x)=0$
思想：等价变化（乘除）使等式左侧化为乘积微分的结果，和化为积的微分
案例：
+ $(4+x)^2y'+2xy=4x$
  左侧形式特殊： $((4+x)^2)'=2x$
  化为： $\frac{\mathrm{d}}{\mathrm{d}x}((4+x)^2y)=4x$
  两边积分： $y=\frac{2x^2+C}{(4+x)^2}$
+ $y'+\frac{1}{2}y=\frac{1}{3}\mathrm{e}^{x/3}$
  乘（尚未知）积分因子：$\mu y' +\frac{1}{2}\mu y=\mu\frac{1}{3}\mathrm{e}^{x/3}$
  观察左侧得到方程： $\mu_x=\frac{1}{2}\mu$
  令（只要一个符合的 $\mu$ 即可） $\mu=\mathrm{e}^{x/2}$
  得到： $\frac{\mathrm{d}}{\mathrm{d}x}(\mathrm{e}^{x/2}y)=\frac{1}{3}\mathrm{e}^{x/3}$
  两边积分，通解： $y=\frac{3}{5}\mathrm{e}^{x/3}+C\mathrm{e}^{-x/2}$
+ $2y'+xy=2$
  即 $y'+\frac{x}{2}y=1$
  $\mu=\mathrm{e}^{x^2/4}$
  $\mathrm{e}^{x^2/4}y'+\frac{x}{2}\mathrm{e}^{x^2/4}y=\mathrm{e}^{x^2/4}$ 即 $\frac{\mathrm{d}}{\mathrm{d}x}(y\mathrm{e}^{x^2/4})=\mathrm{e}^{x^2/4}$
  (积不出来但)得到形式 $y=\mathrm{e}^{-x^2/4}\int \mathrm{e}^{x^2/4}\mathrm{d}x +C\mathrm{e}^{-x^2/4}$
方法：
条件：（方程）
$$y'+py=q$$
过程：
同时乘以积分因子 $\mu$
$$\mu y'+\mu py=q$$
如果可以化为，得到条件
\begin{equation}
\label{eq:32}
\mu_x=p\mu
\end{equation}
于是， $\frac{\mathrm{d}\mu}{\mu}=p\mathrm{d}x$
（不论常数）可取
\begin{equation}
\label{eq:33}
\mu=\mathrm{e}^{\int p \mathrm{d}x}
\end{equation}
乘回方程，得到
\begin{equation}
\label{eq:34}
\frac{\mathrm{d}}{\mathrm{d}x}(\mu y)=\frac{\mathrm{d}}{\mathrm{d}x}(\mathrm{e}^{\int p \mathrm{d}x}y)=\mu q
\end{equation}
最终解的形式为
\begin{equation}
\label{eq:35}
y=\mathrm{e}^{-\int p\mathrm{d}x}\int \mu q\mathrm{d}x=\mathrm{e}^{-\int p\mathrm{d}x}\int \mathrm{e}^{\int p \mathrm{d}x} q\mathrm{d}x
\end{equation}

*** 分离变量
对于简单的方程，将 x,y 分到方程两边，同时积分
*** 积分因子/恰当方程
**** 恰当方程
转化为全微分方程。
\begin{equation}
\label{eq:17}
M\mathrm{d}x+N\mathrm{d}y=0
\end{equation}
其中 M,N 关于 x,y 连续且可微
（具有连续的一阶偏导数）

我们希望找到一个恰当的函数 u ，使得 $M=\frac{\partial u}{\partial x},\quad N=\frac{\partial u}{\partial y}$
也就是
\begin{equation}
\label{eq:21}
\begin{split}
\frac{\partial u}{\partial x}\mathrm{d}x+\frac{\partial u}{\partial y}\mathrm{d}y &=0\\
\mathrm{d}u&=0
\end{split}
\end{equation}
所以得到隐式解 $u=C$

\paragraph{条件}
方程满足：
$$\frac{\partial M}{\partial y}=\frac{\partial N}{\partial x}$$

\paragraph{案例}
+ $(y\cos x+2x\mathrm{e}^{y})+(\sin x+x^2\mathrm{e}^{y}-1)y'=0$
  验证： $\frac{\partial y\cos x+2x\mathrm{e}^{y}}{\partial y}=\cos x +2x\mathrm{e}^{y}=\frac{\partial \sin x+x^2\mathrm{e}^{y}-1}{\partial x}$
  求解原函数：偏积分
  $$u=\int y\cos x+2x\mathrm{e}^{y} \mathrm{d}x=-y\sin x+\mathrm{e}^yx^2+C(y)$$
  对另一项（y）偏导
  $$\sin x+x^2\mathrm{e}^{y}-1=\frac{\partial u}{\partial y}=-\sin x+x^2\mathrm{e}^y+C'$$
  $$C=\int 2\sin x+1 \mathrm{d}y=2y\sin x+y$$
  通解： $-y\sin x+\mathrm{e}^yx^2+2y\sin x+y=A$

\paragraph{特殊形式}
一些全微分
fn
\begin{eqnarray}
\label{eq:36}
yx^{y-1}\mathrm{d}x+x^y\ln x \mathrm{d}y=\mathrm{d}x^{y}\\
\frac{y\mathrm{d}x-xdy}{y^{2}}=d(\frac{x}{y})\\
\frac{y\mathrm{d}x-xdy}{yx}=d(\ln \left| \frac{x}{y} \right|)\\
\frac{y\mathrm{d}x-xdy}{x^{2}+y^{2}}=d(arctan \frac{x}{y})\\
\frac{y\mathrm{d}x-xdy}{x^{2}+y^{2}}=\frac{1}{2}d(\ln \left| \frac{x-y}{x+y} \right|
\end{eqnarray}
$yx^{y-1}\mathrm{d}x+x^y\ln x \mathrm{d}y=\mathrm{d}x^{y}$
$\frac{y\mathrm{d}x-xdy}{y^{2}}=d(\frac{x}{y})$
$\frac{y\mathrm{d}x-xdy}{yx}=d(\ln \left| \frac{x}{y} \right|)$
$\frac{y\mathrm{d}x-xdy}{x^{2}+y^{2}}=d(arctan \frac{x}{y})$
$\frac{y\mathrm{d}x-xdy}{x^{2}+y^{2}}=\frac{1}{2}d(\ln \left| \frac{x-y}{x+y} \right|$
**** 积分因子
区别之前，这里是找到原函数，之前是将方程左侧化为
－可以求解所有方程，但不一定可以解出
不是恰当的方程转化为恰当
把
ref
乘以 $\mu$
得到
\begin{equation}
\label{eq:25}
\mu M\mathrm{d}x+\mu N\mathrm{d}y=0
\end{equation}

必要条件
\begin{equation}
\label{eq:23}
\frac{\partial \mu M}{\partial y}=\frac{\partial \mu N}{\partial x}
\end{equation}

找法
假设 $\mathrm{d}u=$
$\mu_y M+\mu M_y=\mu_x N+\mu N_x$
(不会解方程，化简形式，令某些项为0)找一个只与 x 或 y 有关的积分因子
只与 x 相关的积分因子
$\mu_xN=\mu(M_y-N_x)$
\begin{equation}
\label{eq:24}
\frac{1}{\mu}\frac{\mathrm{d}\mu}{\mathrm{d}x}
=\frac{(M_y-N_x)}{N} 
\end{equation}
\begin{equation}
\label{eq:26}
\mu=\mathrm{e}^{\int \frac{(M_y-N_x)}{N} \mathrm{d}x}
\end{equation}

\paragraph{案例}
+  $(3xy+y^2)+(x^2+xy)y'=0$ [完整]
  验证发现非恰当： $\frac{\partial 3xy+y^2}{\partial y}=3x+2y\neq2x+y= \frac{\partial x^2+xy}{\partial x}$
  写出积分因子方程： $\mu_y M+\mu M_y=\mu_x N+\mu N_x$
  即 $\mu_y (3xy+y^{2})+\mu (3x+2y)=\mu_x (x^2+xy)+\mu (2x+y)$
  取 $\mu_y=0$
  得 $\mu(x+y)=\mu_x(x^2+xy) \rightarrow \mu=x\mu_x$
  于是令 $\mu=x$
  得恰当方程
  M 对 x 偏积分 $u=\int 3x^2y+xy^2\mathrm{d}x=x^3y+\frac{1}{2}x^2y^2+c(y)$
  u 对 y 偏导 
  解为 $x^3y+\frac{1}{2}x^2y^2=C$
**** 原理
***** 恰当方程的判据
判断
ref
是(具有连续一阶偏导)
是恰当微分方程（可以转化为 $\mathrm{d}u=0$）的充分必要条件 $$\frac{\partial M}{\partial y}=\frac{\partial N}{\partial x}$$

ref
具有一般性

充分：
满足条件则能够找到一个 u 使得  $M=\frac{\partial u}{\partial x},\quad N=\frac{\partial u}{\partial y}$

找 u
对 M 向 x 积分，取原函数为 u， $u=\int M \mathrm{d}x +C$
(C 与 x 必然无关)可以认为  $u(x,y)=\int M(x,y) \mathrm{d}x +C(y)$
+如果 C 的确只与 y 有关那么+
(我们希望 $\mathrm{d}u-\frac{\partial u}{\partial x}\mathrm{d}x=\mathrm{d}C=\mathrm{d}C(y)$ 这个 dC 与 dx 无关，就的确说明找到的函数 u 它的全微分是原方程，便得证)
# 格式？
研究 C ，（无法直接得到 dC 只好先算 u 偏导）将所得结果对 y 求偏导

$\frac{\partial u}{\partial y}=\frac{\partial\int M \mathrm{d}x}{\partial y}+\frac{\mathrm{d}C}{\mathrm{d}y}=N$
所以 $\frac{\mathrm{d}C}{\mathrm{d}y}=N-\frac{\partial}{\partial y}\int M \mathrm{d}x$

证明它与 x 无关
于是它就是全微分
，使用偏导为0验证
\begin{equation}
\label{eq:22}
\begin{split}
\frac{\partial}{\partial x}[N-\frac{d}{\mathrm{d}y}\int M \mathrm{d}x] &=\frac{\partial}{\partial x}N-\frac{\partial}{\partial x}\frac{\partial}{\partial y}\int M \mathrm{d}x\\
&=\frac{\partial N}{\partial x}-\frac{\partial}{\partial y}\frac{\partial}{\partial x}\int M \mathrm{d}x \\
&=\frac{\partial N}{\partial x}-\frac{\partial M}{\partial y}=0
\end{split}
\end{equation}
于是 dC 与 x 无关，得证 u 的全微分是原方程。
x,y 对称，证明具有一般性。

必要：
如果是恰当方程那么已经存在函数 u ，它的全微分是原方程，那么
可以
根据
Cla
克莱罗定理
fn
验证两者相等

** 高阶方程
** 二阶方程
以下方法，
齐次方程的特解为0，只需要考虑非齐次情况
*** 特征方程：通解
试用范围：齐次方程求通解
原理：
\paragraph{具体过程}
首先使用 $\mathrm{e}^{\lambda x}$ 试探方程的解，得到代数方程，即它的特征方程。使用代数方程解得 $\lambda$ 得到通解
\paragraph{特殊情况}
如果出现重根，
相当于少了一些解，因此我们需要补齐至方程阶数的解
# 为什么？
，那么可以猜测这些需要添加的解形式和 $\mathrm{e}^{\lambda x}$ 类似，可以尝试发现 $x\mathrm{e}^{\lambda x}$ 满足方程，
则根据重数使用如 $x\mathrm{e}^{\lambda_{p} x},\cdots,x^{(p-1)}\mathrm{e}^{\lambda_{p}x}$ 的形式扩展解的数目，补满 n 个，假设  $\lambda_p$ 有 p 重根，就添加额外 p-1 个解如前。
#+begin_example

#+end_example
*** 积分因子/二阶恰当方程
**** TODO 案例

**** 原理
方程为
\begin{equation}
\label{eq:14}
P(x)y''+Q(x)y'+R(x)y=0
\end{equation}
希望转化为（一阶恰当方程的形式 $M\mathrm{d}x+N\mathrm{d}y=0$）
\begin{equation}
\label{eq:15}
(P(x)y')'+(f(x)y)'=0
\end{equation}
可知
\begin{equation}
\label{eq:18}
P'y'+Py''+f'y+fy'=0
\end{equation}
条件为
\begin{align*}
P'+f'=Q\\
f'=R
\end{align*}
得到条件
\begin{equation}
\label{eq:19}
P''-Q'+R=0
\end{equation}
实际代入计算
\begin{equation}
\label{eq:20}
f=Q-P'
\end{equation}

*** TODO 换自变量
Euler 方程
(\ref{eq:EulerEqu})
一般形式
#+begin_comment
太多项
#+end_comment

** 求非齐次特解

*** 待定系数法
\paragraph{概要}
非齐次方程观察右端项，猜测可能形式（采取相同相似形式），代入解出系数。
# 表格。。
需要考虑重根和与齐次通解重复的部分。如果有重复。

\paragraph{举枚}
+ $y''-3y'-4y=3\mathrm{e}^{2x}$
通解 $\mathrm{e}^{-x},\mathrm{e}^{4x}$
猜特解形式 $Y_p=A\mathrm{e}^{2x}$
代入
\begin{equation}
\label{eq:6}
4A+6A-4A=3
\end{equation}
通解为 $y=\frac{1}{2}\mathrm{e}^{2x}+C_1\mathrm{e}^{-x}+C_2\mathrm{e}^{4x}$

+ $y''-3y'-4y=3\mathrm{e}^{2x}$
   原特解与齐次通解相同，特解取 $Y_p=Ax\mathrm{e}^{2x}$ 解得 $A=-\frac{2}{5}$

+ $y''-3y'-4y=3\mathrm{e}^{2x}+2\sin x-8\mathrm{e}^x\cos 2x$
   分别计算

+ $y'''-4y'=x+3\cos x+\mathrm{e}^{-2x}$
   齐次通解： 0,2,-2
   $g(x)=x+3\cos x+\mathrm{e}^{-2x}$
  1. 与0重  $Y_{p1}=x(A_0+A_1x)$
  2. $Y_{p2}=B\cos x+C\sin x$
  3. 与－2重 $Y_{p3}=Ex\mathrm{e}^{-2x}$

+ $y^{(4)}+2y''+y=3\sin x-5\cos x$
  齐次通解： $(r^2+1)^2=0\Rightarrow r=\pm \mathrm{i}$
  $y_h=\cos x+\sin x+x\cos x+x\sin x$
  特解： $Y_p=x^2(A\cos x+B\sin x)$
     
*** 常数变易法
使用已经解得的通解，视常数为含自变量的函数，代入方程继续求解。

\textbf{简化思路：[核心]}有 n 个系数需要确定，所以需要 n 方程，可以自由取这些方程。

\paragraph{技巧}
使用 Wronski 行列式


**** TODO 为什么

约束方程，令所有 $c'_iy^n_i=0$ ，本质上是代入方程后使每次求导让系数求导的项为0。

最后结果是 Wronski 行列式

\begin{eqnarray*}
\label{eq:2}
\sum c'_iy_i^1=0\\
\sum c'_iy_i^2=0\\
\cdots\\
\sum c'_iy_i^{n-1}=0
\end{eqnarray*}
可化为：

\begin{equation}
\label{eq:5}
\begin{pmatrix}
y_1&y_2&\cdots&y_n\\
y'_1&y'_2&\cdots&y'_n\\
\vdots&&\cdots&\vdots\\
y^{(n-1)}_1&y^{(n-1)}_2&\cdots&y^{(n-1)}_n
\end{pmatrix}
\begin{pmatrix}
c_1\\c_2\\\vdots\\c_n
\end{pmatrix}
=
\begin{pmatrix}
0\\0\\\vdots\\0
\end{pmatrix}
\end{equation}

之后利用 Crammer 法则求解 $c_i=\frac{|W(i)|}{|W|}$ 。
*** 归零因子法（A）
\paragraph{概要}
化非齐次方程为齐次方程
消去方程右边项
代价是方程阶数升高
\paragraph{举例}
使用 $D$ 微分算子
+ $(D-2)^2(D+1)y=3\mathrm{e}^{2x}-x\mathrm{e}^{-x}$
  右侧第一项 $\mathrm{e}^{2x}$ : D-2
  第二项 $x\mathrm{e}^{-x}$ : $(D+1)^2$
  于是归零因子为： $(D+1)^2(D-2)$
  两边同乘归零因子得到： $(D+1)^3(D-2)^4y=0$
  就解7阶齐次方程，注意可能有增根
  7阶通解： $y_h=(c_1)

** 幂级数解法

*** 幂级数
形式： $$\sum_{i=0}^{\infty}=a_n(x-x_0)^{n}$$
原理定理保证： ref
\paragraph{收敛半径的计算}
+ 比值
  \begin{equation}
  \label{eq:3}
  \lim_{n\rightarrow\infty}\left| \frac{a_{n+1}(x-x_0)^{n+1}}{a_n(x-x_0)^{n}} \right|=(x-x_0)\lim_{n\rightarrow\infty}\left| \frac{a_{n+1}}{a_n} \right|
  \end{equation}
+ 根值
  \begin{equation}
  \label{eq:11}
  \lim_{n\rightarrow\infty}\sqrt[n]{\left| a_n(x-x_0)^{n} \right|}=(x-x_0)\sqrt[n]{\left| a_n \right|}
  \end{equation}

变换求和哑元，保证 x 的次方相同于是可以把 x 约掉，只解出系数的递推关系

如果 x 次方相同，仇和其实不一样，把多出来的项取出来，令它们为0，使得下标相同，去掉求和，得递推。
\paragraph{性质}
条件：收敛级数， $f(x)=\sum a_n(x-x_0)^n$

+ 可加减乘除（保持收敛）
+ 连续的 $f(x)$ 在收敛区间上有各阶导数。
+ 是解析的 $\rightarrow$ 可泰勒展开
+ 两个级数相等，对应次方的系数相等

$$P(x)y''+Q(x)y'+R(x)y=0$$  
P Q R
多项式 $\rightarrow$ 解析的

常点 : ordinary point
$P(x_0)$

Wronski
$W[Y,y](x_0)$

\begin{equation}
\label{eq:16}
y''+k^2y=0
\end{equation}


*** 特殊方程
**** Airy
# 不会：

**** Legrendre
**** Berssel
***  Euler 方程
形式：
\begin{equation}
\label{eq:EulerEqu}
x^2y''+\alpha xy' +\beta y=0,\quad x>0
\end{equation}
引入中间变量 x
#+begin_comment
独立变量？
#+end_comment
$$x=\mathrm{e}^t,\quad t=\ln x$$
于是各项关系为
\begin{equation}
\label{eq:9}
\frac{\mathrm{d}t}{\mathrm{d}t}=\frac{1}{x},\quad \frac{\mathrm{d}x}{\mathrm{d}t}=\mathrm{e}^t \rightarrow \frac{\mathrm{d}y}{\mathrm{d}x}=\frac{\mathrm{d}y}{\mathrm{d}t}\frac{\mathrm{d}t}{\mathrm{d}x}=\frac{1}{x}\frac{\mathrm{d}y}{\mathrm{d}t}
\end{equation}

$$\frac{\mathrm{d}^2y}{\mathrm{d}x^2}=\frac{\mathrm{d}}{\mathrm{d}x}(\frac{1}{x}\frac{\mathrm{d}y}{\mathrm{d}t})=-\frac{1}{x^2}\frac{\mathrm{d}y}{\mathrm{d}t}+\frac{1}{x}(\frac{\mathrm{d}t}{\mathrm{d}x}\frac{\mathrm{d}x}{\mathrm{d}t})\frac{\mathrm{d}}{\mathrm{d}x}\frac{\mathrm{d}y}{\mathrm{d}t}=\frac{1}{x^2}(\frac{\mathrm{d}^2y}{\mathrm{d}t^2}-\frac{\mathrm{d}y}{\mathrm{d}t})$$
代入得到
\begin{equation}
\label{eq:10}
\frac{\mathrm{d}^2y}{\mathrm{d}x^2}-\frac{\mathrm{d}y}{\mathrm{d}x}+\alpha \frac{\mathrm{d}y}{\mathrm{d}x}+\beta y=0
\end{equation}
\paragraph{案例}
1. 
** Laplace 变换求解

* 性质定理
** 形式定义
微分算子：
\begin{equation}
\label{eq:7}
L[y]:= \sum_i^n a_i y^{(i)} =
\end{equation}
特征多项式：
\begin{equation}
\label{eq:8}
Z(r):=\sum_i^n a_i r^i
\end{equation}
特征方程：

\begin{gather}
\label{eq:12}
Z(r)  =  0\\
a_n(r-r_1)^{s_1}\cdots(r-r_k)^{s_k}(r-(\lambda_1+\mathrm{i}\mu_1))^{\tau_1}(r-(\lambda_1-\mathrm{i}\mu_1)^{\tau_1}\cdots(r-(\lambda_l\pm\mathrm{i}\mu_l)^{\tau_l}=0
\end{gather}

阶数
\begin{equation}
\label{eq:13}
n=Deg \quad Z=s_1+\cdots+s_k+2(\tau_1+\tau_l)
\end{equation}

** 存在唯一性定理
#+begin_export latex
{\bf 多项式、代数基本定理 }
#+end_export

将一般的 $f(x,y^{(n)},\cdots,y)=0$ 作因式分解如下：

\begin{eqnarray}
\label{eq:1}
a_ny^{(n)}+ a_{n-1}y^{(n-1)}+\cdots+a_1y' a_0y& = & 0 \nonumber\\
a_n \frac{\mathrm{d}^ny}{\mathrm{d}x^n} + a_{n-1}\frac{\mathrm{d}^{n-1}y}{\mathrm{d}x^{n-1}}+\cdots+a_1 \frac{\mathrm{d}y}{\mathrm{d}x}+a_0y & = & 0 \nonumber\\
(b_1 \frac{\mathrm{d}}{\mathrm{d}x}+c_1)(b_2 \frac{\mathrm{d}}{\mathrm{d}x}+c_2)\cdots(b_n \frac{\mathrm{d}}{\mathrm{d}x}+c_n)y & = & 0
\end{eqnarray}

可以分解因式由
？保证，
然后可以利用代数基本定理确保我们必定得到。

直观上看，取最右边与 y 乘的项，得到为0，于是（每一项可以交换下）
\begin{equation}
\label{eq:31}
(b_i \frac{\mathrm{d}}{\mathrm{d}x}+c_i)y  =  0
\end{equation}
可以解出 n 个解。
(同时可以从一个角度说明使用 $\mathrm{e}^{\lambda x}$ 尝试方程的合理性：
$\frac{\mathrm{d}y}{\mathrm{d}x}=-\frac{c_i}{b_i}y$ 可以解出指数形式解)
fn 完备

线性方程：整体
非线性：局部解

#+begin_export latex
{\bf 皮卡序列}
#+end_export

核心：把初值条件代入反复积分函数叙列趋近

\paragraph{方法}
条件：
初值田间

步骤
1. 代入初值
2. 积分
$$\varphi_{n+1}=\int\limits_0^tf(s,\varphi_n(s))\mathrm{d}s$$   

\paragraph{案例}
+
  
Lipschitz 条件
存导函数有界

偏导拆连续且存在
? Langrange 中值定理


先正收敛，再唯一

反例？

** 线性性质
行列式

*** 叠加原理
** Wronski 行列式判断线性相关性
*** TODO 
现在假设解得齐次（通）解 $y_1,\cdots,y_n$ ，代入方程得到
\begin{eqnarray*}
a_ny_{1}^{(n)}+ a_{n-1}y_{1}^{(n-1)}+\cdots+a_1y_{1}'+a_0y_{1} & = & 0 \nonumber\\
\cdots\\
a_ny_{n}^{(n)}+ a_{n-1}y_{2}^{(n-1)}+\cdots+a_1y_{n}'+a_{0}y_{n} & = & 0 \nonumber\\
\end{eqnarray*}
共 n 个方程。它们系数为原微分方程系数万们可以用矩阵改写为 $Ax=0$ 的形式
\begin{equation}
\label{eq:4}
\begin{pmatrix}
y_1&y_2&\cdots&y_n\\
y_1'&y_2'&\cdots&y_n'\\
\vdots&&\cdots&\vdots\\
y^{(n-1)}_1&y^{(n-1)}_2&\cdots&y^{(n-1)}_n\\
\end{pmatrix}^T
\begin{pmatrix}
a_0\\a_1\\\vdots\\a_n
\end{pmatrix}
=
\begin{pmatrix}
0\\0\\\vdots\\0
\end{pmatrix}
\end{equation}

因此根据线性方程的性质，我们要求 $|A|=0$ （理由是 $a_0,\cdots,a_n$ 不全为0，所以 $A$ 存在线性相关部分），即
\begin{equation}
\label{eq:wronski=0}
\begin{vmatrix}
y_1&y_2&\cdots&y_n\\
y_1'&y_2'&\cdots&y_n'\\
\vdots&&\cdots&\vdots\\
y^{(n-1)}_1&y^{(n-1)}_2&\cdots&y^{(n-1)}_n\\
\end{vmatrix}
=0
\end{equation}

此即 Wronski 行列式，可以方便地在微分方程求解中判断解是否线性相关。

线性相关原始定义为：存在线性组合结果为0。即一般的函数应当使用如下判据：
$c_1y_1+\cdots+c_ny_n=0$ 当且仅当 $c_1=c_2=\cdots=c_n=0$ 

#+begin_example 反例
如果不是微分方程的解，使用 Wronski 行列式可能会有问题如：
（此处存疑）
#+end_example

** Abel 定理
效果：不需要解方程就可以得到 Wronski 行列式

** 幂级数收敛

** 奇点
找
正则
每一项是有限的

无穷远
意义？

* 求数值解

** Euler 方法（欧拉折线）
适用：初值条件问题 IVP

原理：解的唯一性

思想：直线近似，缩小步长逼近

效果：一阶？

方法：

- 已有条件：
\begin{gather}
\label{eq:29}
\frac{\mathrm{d}y}{\mathrm{d}x}=f(x,y)\\
y(x_0)=y_0
\end{gather}
(初值条件)

- 过程：
  取步长 $h$
  从方程得到在 $(x_{0},y_0)$ 的导数 $y'=f(x_0,y_0)$
  使用直线方程 $y=f(x_0,y_0)(x-x_0)+y_0$
  代入 $x_0+h$ 计算得到 y 重复

- 公式
  \begin{equation}
  \label{eq:30}
  y_{n+1}=y_n+fh
  \end{equation}
性质：
收敛性
略
#（不会）
# ** 塔克拉格哥
